image: gradle:6.6.1-jdk8

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

test:
  stage: test
  script: gradle --build-cache check --stacktrace
  only:
    - master
    - merge_requests
  cache:
    key: "$CI_PIPELINE_ID"
    policy: push
    paths:
      - build
      - .gradle

release:gradlePluginPortal:
  stage: deploy
  script: gradle publishPlugins -Pgradle.publish.key="$GRADLE_PUBLISH_KEY" -Pgradle.publish.secret="$GRADLE_PUBLISH_SECRET" --stacktrace
  only:
    - master
  cache:
    key: "$CI_PIPELINE_ID"
    policy: pull
    paths:
      - build
      - .gradle

release:bintray:
  stage: deploy
  script: gradle gitLabRelease -Ppublish=true -Poverride=false --stacktrace
  only:
    - master
  cache:
    key: "$CI_PIPELINE_ID"
    policy: pull
    paths:
      - build
      - .gradle
